# Generated by Django 4.2.3 on 2023-07-06 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skill',
            table='main_skill',
        ),
    ]
